### ISSUE TITLE
Ссылки в первом же сообщении

### ISSUE THREAD

**Issue by IlyaOsotov** [vetermanve/gatekeeper_bot#1]
Бывают боты, которые при коннекте сразу отправляют спам в виде ссылки. Если дописать бота, чтобы он выкидывал и спамера и сообщение, если в первом же сообщении была спам ссылка, будет ли это корректно в рамках данного бота?

**Comment by vetermanve** [comment]
В целом да, можно. Можно дописать приветственный текст и просто удалять выкидывать пользователя если в теле первого сообщения есть ссылка. Очень нужно?

**Comment by vetermanve** [comment]
Кхм, я подумаю, если ни у кого не будет от этого проблем (тут есть одни которые хотят чтобы им скидывали ссылку на линкедин в первом сообщении) то я запилю.

**Comment by vetermanve** [comment]
Я начал дописывать бота чтобы он выкидывал тех кто ссылки пишет в приветственном. 
Так же я создал чатик для поддержки бота https://t.me/gateGuardSupport там можно будет обсудить что-то.

**Comment by vetermanve** [comment]
@IlyaOsotov Готово, можешь проверить если хочешь )))
